### ISSUE TITLE
Add a legion build to travis

### ISSUE THREAD

**Issue by junghans** [losalamos/flecsi#55]
We should add a legion build to travis! @spad12 will give me some details on how to build legion using cmake and this will be piece of cake.

\cc @ipdemes @tuxfan

**Comment by spad12** [comment]
So I think the major issue is going to be installing GASNET. 
Here are the commands that should let you build legion from cmake:
git clone https://github.com/StanfordLegion/legion.git
git checkout cmake
mkdir build
cd build
cmake GASNET_ROOT=PATH_TO_GASNET CMAKE_INSTALL_PREFIX=../install ..
make
make install

*Note, the cmake script here registers something with usr/local/cmake/realmTargets.cmake so that other cmake builds can find the legion package install directory and configuration options. I'm not entirely sure how to change where this stuff gets registered to.
